// Single source of truth for every shipped asset. The browser loaders
// (AssetLoader, Sfx, Voice) and scripts/check_assets.mjs both read this file;
// the build fails when public/assets and these tables drift apart.

// Vehicle sprite registration contract, shared by Vehicle.js drawing and the
// check:assets dimension validator. scripts/process_art.py mirrors these two
// numbers: sprites are (length + 2*overhang) x (width + 2*overhang) world
// units at SPRITE_PX_PER_UNIT pixels per unit, painted body centered, so the
// art and the collision footprint coincide exactly at any heading.
export const SPRITE_PX_PER_UNIT = 2;
export const SPRITE_OVERHANG = 6;

export const SPRITE_MANIFEST = Object.freeze({
  vehicle_sports: 'vehicle_sports.png',
  vehicle_pickup: 'vehicle_pickup.png',
  vehicle_taxi: 'vehicle_taxi.png',
  vehicle_police: 'vehicle_police.png',
  vehicle_fire: 'vehicle_fire.png',
  vehicle_icecream: 'vehicle_icecream.png',
  vehicle_ev: 'vehicle_ev.png',
  vehicle_bus: 'vehicle_bus.png',
  vehicle_tow: 'vehicle_tow.png',
  ground: 'ground.jpg',
  building: 'building.png',
  wash: 'wash.png',
  charge: 'charge.png',
  air: 'air.png',
  lift: 'lift.png',
  booth: 'booth.png',
  door: 'door.png',
  bell: 'bell.png',
  title_logo: 'title_logo.png',
  pet_sit: 'pet_sit.png',
  pet_walk: 'pet_walk.png',
  pet_sleep: 'pet_sleep.png',
  portrait_sports: 'portrait_sports.png',
  portrait_pickup: 'portrait_pickup.png',
  portrait_taxi: 'portrait_taxi.png',
  portrait_police: 'portrait_police.png',
  portrait_fire: 'portrait_fire.png',
  portrait_icecream: 'portrait_icecream.png',
  portrait_ev: 'portrait_ev.png',
  portrait_bus: 'portrait_bus.png',
  portrait_tow: 'portrait_tow.png',
});

export const VOICE_LINES = Object.freeze([
  'air_done_bright',
  'air_done_deep',
  'air_done_warm',
  'air_time_bright',
  'air_time_deep',
  'air_time_warm',
  'battery_help_bright',
  'battery_help_deep',
  'battery_help_warm',
  'charge_done_bright',
  'charge_done_deep',
  'charge_done_warm',
  'charge_time_bright',
  'charge_time_deep',
  'charge_time_warm',
  'fixed_thanks_bright',
  'fixed_thanks_deep',
  'fixed_thanks_warm',
  'flat_help_bright',
  'flat_help_deep',
  'flat_help_warm',
  'garage_welcome',
  'good_night',
  'hello_park_bright',
  'hello_park_deep',
  'hello_park_warm',
  'hooray_all_done',
  'lift_done_bright',
  'lift_done_deep',
  'lift_done_warm',
  'lift_time_bright',
  'lift_time_deep',
  'lift_time_warm',
  'nice_spot_bright',
  'nice_spot_deep',
  'nice_spot_warm',
  'thats_me_bright',
  'thats_me_deep',
  'thats_me_warm',
  'tow_rescue',
  'wash_done_bright',
  'wash_done_deep',
  'wash_done_warm',
  'wash_time_bright',
  'wash_time_deep',
  'wash_time_warm',
]);

export const SFX_CLIPS = Object.freeze([
  'air_pump',
  'air_wrench',
  'alarm_chirp',
  'backup_beeper',
  'car_snore',
  'cat_chirp',
  'charge_plug',
  'charger_hum',
  'confetti_pop',
  'doorbell',
  'engine_ev',
  'engine_heavy',
  'engine_pickup',
  'engine_small',
  'engine_sports',
  'garage_door_close',
  'garage_door_open',
  'horn_bus',
  'horn_ev',
  'horn_fire',
  'horn_icecream',
  'horn_pickup',
  'horn_police',
  'horn_sports',
  'horn_taxi',
  'horn_tow',
  'lift_hydraulics',
  'party_horns',
  'pickup_bell',
  'siren_chirp',
  'tow_clunk',
  'wash_brushes',
  'water_spray',
]);
